In [36]:
import pandas as pd 
import zebra
import numpy as np

In [79]:

# Get Initial Partner solver weights. Provide a data source. The Data source is typically the location of the file which contains the partner and solver data

def inital_partner_solver_weights(data_source): 

    partners_df = pd.read_excel(data_source, sheet_name="Partner Data")
    solver_df = pd.read_excel(data_source, sheet_name="Solver Team Data")

    ch_partners_challenges = zebra.get_ch_partners(partners_df)

    # Get Solver Challenges
    ch_solver = zebra.get_ch_solvers(solver_df)

    # # Generate pivot table
    # challenges_pivot, challenges_pivot_copy = zebra.pivot_table_challenges(ch_solver, ch_partners_challenges, export_path, export=False)

    merged_df = pd.merge(ch_solver,
                             ch_partners_challenges,
                             left_on="Challenge",
                             right_on='Challenge',
                             how='outer')
    merged_pivot_table = pd.pivot_table(merged_df,
                                            values="Challenge",
                                            index=["Org_y"],
                                            columns=["Org_x"],
                                            aggfunc=np.sum)


    challenges_pivot = merged_pivot_table.copy()
    challenges_pivot[:] = 1
    challenges_pivot_unpivoted = challenges_pivot.reset_index()
    unpivoted_inital_table = pd.melt(challenges_pivot_unpivoted, id_vars="Org_y")
    zero_column = unpivoted_inital_table['value']
    unpivoted_inital_table = unpivoted_inital_table.assign(geo_score=zero_column, 
                            challenge_score=zero_column,
                            needs_score=zero_column, 
                            stage_score=zero_column)
    partners_solvers_weights =  unpivoted_inital_table.drop(columns='value')

    return partners_solvers_weights


data_source = "../app/mock_input_data.xlsx"
inital_partner_solver_weights(data_source)

/media/pawan/e7/Data_science/colaberry/MIT_Solve_dashboard/notebooks/zebra.py:256: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ch_partners["Challenge Preference"] =  ch_partners["Challenge Preference"].str.split(",")

,Org_y,Org_x,geo_score,challenge_score,needs_score,stage_score
0,Aditya Birla Group,AIR-INK: Air-Pollution to ink,1,1,1,1
1,BMW Foundation Herbert Quandt,AIR-INK: Air-Pollution to ink,1,1,1,1
2,Buenos Aires Innovation Park (City of Buenos A...,AIR-INK: Air-Pollution to ink,1,1,1,1
3,C L Sandberg & Associates,AIR-INK: Air-Pollution to ink,1,1,1,1
4,Capital One,AIR-INK: Air-Pollution to ink,1,1,1,1
...,...,...,...,...,...,...
1275,Terranova Corporation,change:WATER Labs' iThrone: a waste-shrinking ...,1,1,1,1
1276,The Kroger Co. Zero Hunger Zero Waste Foundation,change:WATER Labs' iThrone: a waste-shrinking ...,1,1,1,1
1277,The Pershing Square Foundation,change:WATER Labs' iThrone: a waste-shrinking ...,1,1,1,1
1278,Uber,change:WATER Labs' iThrone: a waste-shrinking ...,1,1,1,1
1279,Yum! Brands,change:WATER Labs' iThrone: a waste-shrinking ...,1,1,1,1

In [77]:
partners_solvers_weights

,Org_y,Org_x,geo_score,challenge_score,needs_score,stage_score
0,Aditya Birla Group,AIR-INK: Air-Pollution to ink,1,1,1,1
1,BMW Foundation Herbert Quandt,AIR-INK: Air-Pollution to ink,1,1,1,1
2,Buenos Aires Innovation Park (City of Buenos A...,AIR-INK: Air-Pollution to ink,1,1,1,1
3,C L Sandberg & Associates,AIR-INK: Air-Pollution to ink,1,1,1,1
4,Capital One,AIR-INK: Air-Pollution to ink,1,1,1,1
...,...,...,...,...,...,...
1275,Terranova Corporation,change:WATER Labs' iThrone: a waste-shrinking ...,1,1,1,1
1276,The Kroger Co. Zero Hunger Zero Waste Foundation,change:WATER Labs' iThrone: a waste-shrinking ...,1,1,1,1
1277,The Pershing Square Foundation,change:WATER Labs' iThrone: a waste-shrinking ...,1,1,1,1
1278,Uber,change:WATER Labs' iThrone: a waste-shrinking ...,1,1,1,1
1279,Yum! Brands,change:WATER Labs' iThrone: a waste-shrinking ...,1,1,1,1